CREATE DATABASE IF NOT EXISTS corewar;

USE corewar;

CREATE TABLE IF NOT EXISTS champion (
  id BIGINT UNSIGNED NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  comment VARCHAR(255) NOT NULL,
  box_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);
